### ISSUE TITLE
Don't use promises if is not strictly necessary

### ISSUE THREAD

**Issue by rpadovani** [dottorblaster/tumbledown#1]
In the function `post` in *lib/tumblr.js* you have something like this:

```javascript
return new Promise((resolve, reject) => {
    client().createTextPost(tokenstore.getBlog(), opts)
        .then((res) => {
		resolve(res)
	}).catch((err) => {
		reject(err)
	})
})
```

This is an anti-pattern: you are taking the result (and the error) of the promise and passing up as they are, adding an useless promise to the event stack.

You just need to return your original promise:

```javascript
function post(data, title) {
	const opts = {
		type: 'text',
		format: 'markdown',
		title: title,
		body: data
	};

	return client().createTextPost(tokenstore.getBlog(), opts);
}
```

**Comment by dottorblaster** [comment]
This is actually a good tip, thanks for pointing me at this.

I was writing the code at the airport and left that promise there just for future design. I think you are right, I removed that (and I ensured not to flood the call stack in other places)
